### ISSUE TITLE
Suggestion: Ability to exclude folders and/or exclude files too

### ISSUE THREAD

**Issue by timhussey** [bcanzanella/vscode-openmatchingfiles#1]
Wanted to first say that this is AWESOME!
Thank you for creating this extension!

Can you give us the ability to exclude certain folders from it's search
as well as exclude certain files?

thanks!!!!!!

**Comment by bcanzanella** [comment]
Hi @timhussey! Under the hood, Open Matching Files (OMF) uses the same search api as VSCode's command palette file search. Excluded files/folders in your `.vscode/settings.json` file will also be excluded from an OMF search result. see: https://code.visualstudio.com/docs/getstarted/settings

Example:
```
{
   "files.exclude": {
        "**/node_modules": true,
        "**/bin": true,
        "**/obj": true,
        "**/SomeAnnoyingFileThatAppearsAllOver.txt": true
    },
}
```
Will that work for you?

**Comment by timhussey** [comment]
YOU ARE THE BEST!!!
I had no idea there was that capability in there!
THANK YOU!!!!!!!
![thank you](https://media.giphy.com/media/26FPOogenQv5eOZHO/giphy.gif)

**Comment by bcanzanella** [comment]
Hehe, no problem. Thanks for bringing it up though, I'll add it to the documentation. Cheers!

**Comment by Preconf** [comment]
@bcanzanella Will it be possible for Open Matching Files (OMF)  to use the search.exclude instead of the files.exclude setting?

files.exclude

Configure glob patterns for excluding files and folders. For example, the files explorer decides which files and folders to show or hide based on this setting.

search.exclude

Configure glob patterns for excluding files and folders in searches. Inherits all glob patterns from the files.exclude setting.

The problem is that I do not want to hide my node_modules folder from the files exlorer but I do want to skip it when searching for files.

Something to consider!

**Comment by bcanzanella** [comment]
@Preconf interesting... I'll have to check that out.

**Comment by GreenGremlin** [comment]
I'm having a similar issue.

> Under the hood, Open Matching Files (OMF) uses the same search api as VSCode's command palette file search.

I believe VSCode's built in file search ignores files in the VCS ignore file (e.g. .gitignore), by default. But this is not the behavior I see with Open Matching Files (OMF). Is it possible to have OMF automatically ignore all files ignored by the VCS?

**Comment by bcanzanella** [comment]
> I'm having a similar issue.
> 
> > Under the hood, Open Matching Files (OMF) uses the same search api as VSCode's command palette file search.
> 
> I believe VSCode's built in file search ignores files in the VCS ignore file (e.g. .gitignore), by default. But this is not the behavior I see with Open Matching Files (OMF). Is it possible to have OMF automatically ignore all files ignored by the VCS?

Version 0.5.0 should now exclude files that are part of your settings.json `files.exclude` as well as the `search.exclude`.
